In [ ]:
import nltk
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
df=pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/UpdatedResumeDataSet.csv')
df.shape

(962, 2)

In [ ]:
df=df.values

In [ ]:
# here first we shuffle our data frame so that when we split our dataframe for training and testing phase 
# there should every type of classes distributed in both phase

np.random.shuffle(df)
shuffled_df=pd.DataFrame(df,columns=['Catagory','Resume'])
shuffled_df

Catagory                                             Resume
0       DevOps Engineer  Software Proficiency: • Languages: Basics of...
1        Java Developer  TECHNICAL SKILLS Skills: Java, SQL, PL/SQL, C,...
2        Civil Engineer  Education Details \r\nJanuary 2005 S.S.C  Bara...
3         ETL Developer  TechnicalProficiencies DB: Oracle 11g Domains:...
4                  Arts  I Other Skills Course/Skill Name Board Year Of...
..                  ...                                                ...
957             Testing  COMPUTER PROFICIENCY • Basic: MS-Office (Pow...
958     DevOps Engineer  Skills VISA B1-VISA (USA) Onsite Visits to Swe...
959               Sales  Skill Sets: • Multi-tasking • Collaborativ...
960  Health and fitness  Personal Skills: • Good verbal and written c...
961       ETL Developer  Education Details \r\nJanuary 2015 Bachelor of...

[962 rows x 2 columns]

In [ ]:
# here we caring about only resume column  and we making a list of resumes

list_resume=list(shuffled_df['Resume'])

** For converting any text document into list of tokens so that they can be used for classifying the classes.**
* we should follw 4 stages which are follows---*
- Convert all the characters into lower case 
- Tokenize them into words
- removing the stopwords
- stemming


### Stage 1- Convert to lower Case

In [ ]:

def to_lower_case(data):
    for words in data:
        clean_text_1.append(str.lower(words))
to_lower_case(list_resume)

### Stage 2- tokenize ,Stopwords removal, stemming

In [ ]:
# nltk is predefined package in python , it is used where we need natural language toolkit
import nltk

**Stopwords** is a list of words which are not useful for classifying our model

In [ ]:
# first we download stopwords 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

there are various type of **Tokenizer** present like sentence tokenizer ,word tokenizer, character tokenizer etc.
- **Sentence Tokenizer** are used to convert a document into tokens of sentences
- **Word Tokenizer** are used to convert a sentences into list of words
- **Character Tokenizer** are used to convert a word into list of characters
- **RegExpTokenizer**  are used to convert a sentence into list of words based on given regular expression

In [ ]:
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

In the above cell we import the stemmer 

**Stemmer** means it converts word into base form of words 

In [ ]:
tokenizer=RegexpTokenizer(r'\w+')
en_stopwords=set(stopwords.words('english'))
ps=PorterStemmer()

In [ ]:
def getCleanedText(text):
    text=text.lower()
    
    # tokenize
    tokens=tokenizer.tokenize(text)
    new_tokens=[token for token in tokens if (token not in en_stopwords)]
    stemmed_tokens=[ps.stem(tokens) for tokens in new_tokens]
    clean_text=" ".join(stemmed_tokens)
    return clean_text

In [ ]:
c_text= [getCleanedText(i) for i in list_resume]

In [ ]:
len(c_text)

962

for each resume we will create a feature vector which has only numbers and the size of the feature vector is number of unique words in all the **clear text** (*c_text*).
**CountVectorizer** function will return a list of feature vectors for each resume .


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()
vectorizer_corpus=cv.fit_transform(c_text)
#vector.append(vectorized_corpus)
vectorized_corpus=vectorizer_corpus.toarray()
vectorized_corpus
## This vectorized Corpus is a feature Vector for each resume

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectorized_corpus

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:

len(cv.vocabulary_)
vector_dict=cv.vocabulary_
sorted_dict=dict(sorted(vector_dict.items(), key=lambda item: item[1]))
new_df=pd.DataFrame(vectorized_corpus,columns=sorted_dict.keys())
new_df

000  01  017  02  03  04  04th  ...  zero  zhypil  zone  zookeep  zz  ã¼  ã¼â
0      0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
1      0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
2      0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
3      0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
4      0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
..   ...  ..  ...  ..  ..  ..   ...  ...   ...     ...   ...      ...  ..  ..  ...
957    0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
958    0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
959    0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
960    0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0
961    0   0    0   0   0   0     0  ...     0       0     0        0   0   0    0

[962 rows x 5510 columns]

In [ ]:
new_df['Label']=shuffled_df['Catagory']
new_df

000  01  017  02  03  04  ...  zone  zookeep  zz  ã¼  ã¼â               Label
0      0   0    0   0   0   0  ...     0        0   0   0    0     DevOps Engineer
1      0   0    0   0   0   0  ...     0        0   0   0    0      Java Developer
2      0   0    0   0   0   0  ...     0        0   0   0    0      Civil Engineer
3      0   0    0   0   0   0  ...     0        0   0   0    0       ETL Developer
4      0   0    0   0   0   0  ...     0        0   0   0    0                Arts
..   ...  ..  ...  ..  ..  ..  ...   ...      ...  ..  ..  ...                 ...
957    0   0    0   0   0   0  ...     0        0   0   0    0             Testing
958    0   0    0   0   0   0  ...     0        0   0   0    0     DevOps Engineer
959    0   0    0   0   0   0  ...     0        0   0   0    0               Sales
960    0   0    0   0   0   0  ...     0        0   0   0    0  Health and fitness
961    0   0    0   0   0   0  ...     0        0   0   0    0       ETL Developer

[962 rows x 5511 columns]

now here we added a column named **"Label"** which is the category of the given dataframe

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

now we need to encode the label with the help of label encoder 

In [ ]:
le= LabelEncoder()
df_encoded=new_df.apply(le.fit_transform,axis=0)
cols=df_encoded.columns

## according to me the words which are starting with any digit that will not be an Important word
filtered_column=[i for i in cols if i[0] not in ['0','1','2','3','4','5','6','7','8','9']]
len(filtered_column)
filtered_df=df_encoded[filtered_column]
filtered_df


a1  a2  aaa  aag  aakruti  ab  ...  zone  zookeep  zz  ã¼  ã¼â  Label
0     0   0    0    0        0   0  ...     0        0   0   0    0      8
1     0   0    0    0        0   0  ...     0        0   0   0    0     15
2     0   0    0    0        0   0  ...     0        0   0   0    0      5
3     0   0    0    0        0   0  ...     0        0   0   0    0     10
4     0   0    0    0        0   0  ...     0        0   0   0    0      1
..   ..  ..  ...  ...      ...  ..  ...   ...      ...  ..  ..  ...    ...
957   0   0    0    0        0   0  ...     0        0   0   0    0     23
958   0   0    0    0        0   0  ...     0        0   0   0    0      8
959   0   0    0    0        0   0  ...     0        0   0   0    0     22
960   0   0    0    0        0   0  ...     0        0   0   0    0     14
961   0   0    0    0        0   0  ...     0        0   0   0    0     10

[962 rows x 5271 columns]

In [ ]:
df_array=filtered_df.values
data_x=df_array[:,:-1]
data_y=df_array[:,-1]
data_x.shape

(962, 5270)

In [ ]:
train_x,test_x,train_y,test_y=train_test_split(data_x,data_y,test_size=0.2)
np.unique(train_y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## now we are going to use predefine Sklearn library for Naive Bayes Theorem

In [ ]:
from sklearn.naive_bayes import MultinomialNB

classifier= MultinomialNB()
classifier.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
predicted_y=classifier.predict(test_x)
sum(predicted_y==test_y)/test_y.shape[0]

0.9896373056994818

In [ ]:
test_y

array([ 7, 11,  9,  6, 24,  9, 13, 19, 23, 23, 15,  4,  6,  8, 13,  3,  8,
        3, 23, 24, 23, 10, 23, 11,  4,  8, 24, 10, 12, 23,  3, 18, 22, 14,
       16,  8, 14,  1,  6, 12, 18,  1,  3,  8, 18,  7, 23, 15, 23,  0, 12,
        1, 16, 24, 22,  8, 11, 15, 15,  6,  9,  3, 14, 20, 21, 22, 15,  7,
       11,  5, 23, 18,  5, 23, 18,  5, 20,  1,  0,  9,  7, 20, 16,  7, 21,
       12, 12, 16, 23, 19, 13, 22,  5, 17, 10,  3, 10,  6, 19,  5, 16, 10,
       22, 15,  1, 13, 21, 12, 14,  1, 15, 20, 24, 17, 10,  6, 12, 20,  8,
       13, 15, 13,  1, 17, 19,  0, 23, 19,  8,  2,  5,  4, 14,  6,  9,  5,
        8, 16, 15,  4,  2,  9, 22,  1, 18,  1, 10, 14, 18, 23, 15, 11, 22,
       17,  6, 14, 15,  7, 13,  1, 17, 23, 19,  2, 16, 19,  5, 21, 23,  3,
       11, 12,  2, 12, 23, 11,  1,  2,  7, 22,  3, 24, 24, 19, 20, 10, 17,
       16, 23, 12, 10, 23, 24])

In [ ]:
def le_inverse_transform(y):
  return le.inverse_transform(y)

def prediction(test_x,classifier):
  predicted_y=classifier.predict(test_x)
  return le_inverse_transform(predicted_y)
  
prediction(test_x,classifier)


array(['Database', 'Electrical Engineering', 'DotNet Developer',
       'Data Science', 'Web Designing', 'DotNet Developer', 'Hadoop',
       'PMO', 'Testing', 'Testing', 'Java Developer', 'Business Analyst',
       'Data Science', 'DevOps Engineer', 'Hadoop', 'Blockchain',
       'DevOps Engineer', 'Blockchain', 'Testing', 'Web Designing',
       'Testing', 'ETL Developer', 'Testing', 'Electrical Engineering',
       'Business Analyst', 'DevOps Engineer', 'Web Designing',
       'ETL Developer', 'HR', 'Testing', 'Blockchain',
       'Operations Manager', 'Sales', 'Health and fitness',
       'Mechanical Engineer', 'DevOps Engineer', 'Health and fitness',
       'Arts', 'Data Science', 'HR', 'Operations Manager', 'Arts',
       'Blockchain', 'DevOps Engineer', 'Operations Manager', 'Database',
       'Testing', 'Java Developer', 'Testing', 'Advocate', 'HR', 'Arts',
       'Mechanical Engineer', 'Web Designing', 'Sales', 'DevOps Engineer',
       'Electrical Engineering', 'Java Develope

## Accuracy Score

In [ ]:
#  predefine accuracy score
classifier.score(test_x,test_y)

0.9896373056994818

In [ ]:
# user define
sum(predicted_y==test_y)/test_y.shape[0]

0.9896373056994818

In [ ]:
named_y=le.inverse_transform(predicted_y)
predicted_y

array([ 7, 11,  9,  6, 24,  9, 13, 19, 23, 23, 15,  4,  6,  8, 13,  3,  8,
        3, 23, 24, 23, 10, 23, 11,  4,  8, 24, 10, 12, 23,  3, 18, 22, 14,
       16,  8, 14,  1,  6, 12, 18,  1,  3,  8, 18,  7, 23, 15, 23,  0, 12,
        1, 16, 24, 22,  8, 11, 15, 15,  6,  9,  3, 14, 20, 21, 22, 15,  7,
       11,  5, 23, 18,  5, 23, 18,  5, 20,  1,  0,  9,  7, 20, 16,  7, 21,
       12, 12, 16, 23, 19, 13, 22,  5, 17, 10,  3, 10,  6, 19,  5, 16, 10,
       22, 15,  1, 13, 21, 12, 14,  1, 15, 20, 24, 17, 10,  6, 12, 20,  8,
       13, 15, 13,  1, 17, 19,  0, 23, 19,  2,  2,  5,  4, 14,  6,  9,  5,
       19, 16, 15,  4,  2,  9, 22,  1, 18,  1, 10, 14, 18, 23, 15, 11, 22,
       17,  6, 14, 15,  7, 13,  1, 17, 23, 19,  2, 16, 19,  5, 21, 23,  3,
       11, 12,  2, 12, 23, 11,  1,  2,  7, 22,  3, 24, 24, 19, 20, 10, 17,
       16, 23, 12, 10, 23, 24])

## user define NAive bayes classifier

In [ ]:
def prior_probability(train_x,train_y,label):
    total_examples=train_x.shape[0]
    class_examples=np.sum(train_y==label)
    return (class_examples/float(total_examples))

In [ ]:
def cond_prob(train_x,train_y,feature_column,feature_value,label):
    x_filtered=train_x[train_y==label]   # only those rows of training data where y_train =class label
    numerator= np.sum(x_filtered[:,feature_column]==feature_value)  # along all filtered rows where value of featur column == feature value
    denomenator=np.sum(train_y==label)    
    return (numerator/float(denomenator))

### Now we are going to Compute the Posterior probability or the prediction

In [ ]:
def predict(x_train,y_train,xtest):
    '''x_test is a single testing point ,n features'''
    n_features=x_train.shape[1]
    post_prob=[]
    classes=np.unique(y_train)
    for label in classes:
        likelihood=1.0
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,xtest[f],label)
            likelihood*=cond
        prior=prior_probability(x_train,y_train,label)
        post=likelihood*prior
        post_prob.append(post)
    pred=np.argmax(post_prob)
    return pred

In [ ]:
predict(train_x,train_y,test_x[0,:])

6